### ISSUE TITLE
🔨Simulation should be able to be defined in YAML

### ISSUE THREAD

**Issue by darkarnium** [darkarnium/kako#2]
In order to more easily create simulations for common services, it should be possible to define simulations from YAML. This should allow for definition of banners and expected command inputs and outputs.

The definitions could look something like the following:

```yaml
---
simulation:
  port: 7547
  listener: 'HTTP'
  interpreter: ''
  routes:
    - 'GET':
      - path: '/'
         response_code: 403
         response_body: 'NOPE'
    - 'POST':
      - path: '/UD/act'
         response_code: 200
         response_body: ''
```
